### ISSUE TITLE
run debug.js error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by daries** [joaomirandasa/whats2api#23]
<img width="573" alt="Screen Shot 2020-05-11 at 07 30 00" src="https://user-images.githubusercontent.com/3004414/81514428-465b9180-9359-11ea-9255-41294e96f885.png">
please help me

**Comment by joaomirandasa** [comment]
First of all, please be a little bit more dedicated to create an issue, you used an poor title and make a messy on declare about what desired. If you be a little bit more dedicated this answers can help another ones in future. So in another words, do not copy and paste error, be smarter and dedicated on this. This job is really hard to keep and this kind of title makes me almost desist.
Okay?! @daries 

Now about your error, it's hapening because puppeter it's not loaded propperly, some steps can help you:
1) Reinstall puppeter manually using 
```node
npm install puppeteer --save
````
2) If first step not fix your troubles, try it:
```bash
sudo apt-get install gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget
```
This above command will install things necessary to run chromium on machine, most part of this errors happening when you run puppeter on VPS and cloud, so it's mandatory try this approachs.

**Comment by Animeliza** [comment]
You can use docker image to avoid that problems too

https://hub.docker.com/r/joaomirandas/whats2api

**Comment by joaomirandasa** [comment]
Exatcly @Animeliza 
That's definelly is the best way to do! 

I will close this issue for a log time of no response from @daries - let us know if anything goes bad.
